version: "3.8"

services:
  django_init_project:
    image: django_init_project:production
    container_name: django_init_project
    build:
      context: ./app
      dockerfile: Dockerfile
    command: gunicorn django_init_project.wsgi:application --bind 0.0.0.0:8000 -w ${NUM_WORKERS:-4}
    volumes:
      - ./static_volume:/home/app/web/staticfiles
      - ./media_volume:/home/app/web/mediafiles
      - ./app/logs:/home/app/web/logs
    ports:
      - ${PORT:-8000}:8000

    restart: unless-stopped
    networks:
      - django_init_project_network
    deploy:
      replicas: 10
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 5s
        # max_attempts: 3
        # window: 120s

  django_init_project_2:
    image: django_init_project:production
    container_name: django_init_project_2
    build:
      context: ./app
      dockerfile: Dockerfile
    command: gunicorn django_init_project.wsgi:application --bind 0.0.0.0:8001 -w ${NUM_WORKERS:-4}
    volumes:
      - ./static_volume:/home/app/web/staticfiles
      - ./media_volume:/home/app/web/mediafiles
      - ./app/logs:/home/app/web/logs
    ports:
      - ${PORT:-8001}:8001

    restart: unless-stopped
    networks:
      - django_init_project_network
    deploy:
      replicas: 10
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 5s
        # max_attempts: 3
        # window: 120s

networks:
  django_init_project_network:
    external: true
