version: "3.8"

services:
  django_init_project:
    image: django_init_project:latest
    build:
      context: ./app
      dockerfile: Dockerfile
    command: python manage.py runserver
    ports:
      - ${PORT:-8000}:8000
    deploy:
      replicas: 10
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
      restart_policy:
        condition: on-failure
