version: "3.8"

services:
  django:
    image: ${REGISTRY}/${IMAGE_NAME}/django-app:${GITHUB_SHA_SHORT}
    command: gunicorn django_init_project.wsgi:application --bind 0.0.0.0:8000 --workers 4
    ports:
      - 8000:8000
    env_file: .env
    # volumes:
    #   - /var/www/${IMAGE_NAME}/media/:/var/www/media/
    depends_on:
      - redis
    deploy:
      replicas: 5
      update_config:
        failure_action: rollback
        order: start-first
      restart_policy:
        condition: on-failure
    networks:
      - swarm-example
  redis:
    image: redis:6-alpine
    deploy:
      replicas: 1
      update_config:
        failure_action: rollback
        order: start-first
      restart_policy:
        condition: on-failure
      placement:
        constraints:
        - node.role==manager
    networks:
      - swarm-example

networks:
  swarm-example:
    driver: overlay